name: Docker Image CI

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        BOT_CONFIG: ${{ secrets.BOT_CONFIG }}      
      run: |
        echo ${BOT_CONFIG} > ./config.json
        docker build . --no-cache --file Dockerfile --tag ${REPO_NAME}
        rm -f ./config.json
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Update running image
      shell: bash
      run: |
        docker stop ${REPO_NAME} || true
        docker rm ${REPO_NAME}
        docker run --detach --restart=always --name=${REPO_NAME} ${REPO_NAME}
