name: docker build

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  CONFIG_PATH: ${{ secrets.CONFIG_PATH }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      run: |
        docker build --tag ${REPO_NAME} .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Update running image
      shell: bash
      run: |
        docker stop ${REPO_NAME} || true
        docker rm ${REPO_NAME} || true
        docker run --name=${REPO_NAME} --detach --restart=always \
        -v ${CONFIG_PATH}:/bot/config.json ${REPO_NAME}
