name: Podman build

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  CONFIG_PATH: ${{ secrets.CONFIG_PATH }}

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build Podman image
      run: |
        podman build --tag ${REPO_NAME} .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Update running container
      shell: bash
      run: |
        podman stop ${REPO_NAME} || true
        podman rm ${REPO_NAME} || true
        podman run --name=${REPO_NAME} \
               --detach --replace \
               --log-opt max-size=10mb \
               --restart=always \
               -v ${CONFIG_PATH}:/bot/config.json:Z \
               ${REPO_NAME}
