name: Docker build

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BOT_CONFIG: ${{ secrets.BOT_CONFIG }}

jobs:
  build:
    runs-on: marilith
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: |
        echo "${BOT_CONFIG}" > config.json
        docker build --tag ${REPO_NAME}:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Update running container
      shell: bash
      run: |
        docker stop ${REPO_NAME} || true
        docker rm ${REPO_NAME} || true
        docker run --name=${REPO_NAME} \
               --detach \
               --restart=always \
               ${REPO_NAME}:latest
