name: get secrets
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: print secrets
      run: |
        echo $BOT_CONFIG >> src/config.json
        cat src/.env
      shell: bash
      env:
        BOT_CONFIG : ${{secrets.BOT_CONFIG}}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: BOT_CONFIG
       path: src/config.json
