name: Podman build

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: ${{ github.event.repository.name }}
  BOT_CONFIG: ${{ secrets.BOT_CONFIG }}

jobs:
  build:
    runs-on: marilith
    steps:
    - uses: actions/checkout@v4
    - name: Build Podman image
      run: |
        echo "${BOT_CONFIG}" > config.json
        podman build --tag ${REPO_NAME}:latest .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Update running container
      shell: bash
      run: |
        podman run --name=${REPO_NAME} \
               --detach --replace \
               --restart=always \
               ${REPO_NAME}:latest
